import axios from 'axios';

async function run() {
  console.log("=== Testing Real Sync to QMetry via Proxy ===");

  const settings = {
    qmetryBaseUrl: "https://aryammurali996.atlassian.net/jira/apps/8b7b816c-2b85-4e73-ae22-aa0e6f0407ec/53926dc7-47de-4878-9fc2-5033dde60120?folderId=-1&projectId=10034&projectKey=CPDSS",
    apiToken: "<YOUR_QMETRY_API_TOKEN>",
    projectId: "CPDSS"
  };

  const testCases = [
    {
      TC_ID: "TC001",
      Scenario_Name: "Successful login with valid credentials",
      Gherkin: "Given the user is on the login page\nWhen the user enters valid username and password\nAnd clicks the login button\nThen the user should be redirected to the dashboard",
      Type: "Happy Path",
      Expected_Result: "User is successfully logged in and redirected to the dashboard"
    },
    {
      TC_ID: "TC002",
      Scenario_Name: "Login with invalid username",
      Gherkin: "Given the user is on the login page\nWhen the user enters an invalid username and valid password\nAnd clicks the login button\nThen an error message should be displayed",
      Type: "Negative",
      Expected_Result: "Error message 'Invalid username or password' is displayed"
    },
    {
      TC_ID: "TC003",
      Scenario_Name: "Login with invalid password",
      Gherkin: "Given the user is on the login page\nWhen the user enters a valid username and invalid password\nAnd clicks the login button\nThen an error message should be displayed",
      Type: "Negative",
      Expected_Result: "Error message 'Invalid username or password' is displayed"
    },
    {
      TC_ID: "TC004",
      Scenario_Name: "Login with empty username",
      Gherkin: "Given the user is on the login page\nWhen the user leaves the username blank and enters a valid password\nAnd clicks the login button\nThen an error message 'Username is required' should be displayed",
      Type: "Negative",
      Expected_Result: "Error message 'Username is required' is displayed"
    }
  ];

  // Helper from frontend to map properties
  const transformToPayload = (tc, jiraKey) => {
    const stepsText = tc.Gherkin || '';
    const lines = stepsText.split('\n').filter(l => l.trim().length > 0);
    const expected = tc.Expected_Result || '';
    
    const steps = lines.map((line, idx) => ({
      stepDetails: line.trim(),
      description: line.trim(),
      testData: '',
      expectedResult: expected,
      id: idx + 1
    }));

    return {
      summary: tc.Scenario_Name,
      name: tc.Scenario_Name,
      description: `Generated by TestPilot AI.\nType: ${tc.Type}`,
      testSteps: steps.map(s => ({ description: s.description, expectedResult: s.expectedResult })),
      steps: steps,
      issueLinks: [jiraKey]
    };
  };

  const results = [];
  for (const tc of testCases) {
    const payload = transformToPayload(tc, "CPDSS-1");
    try {
      const response = await axios.post('http://127.0.0.1:3001/api/qmetry/sync', {
        settings,
        payload,
        jiraKey: "CPDSS-1"
      });
      console.log(`✅ Synced ${tc.TC_ID}:`, response.status, response.data.key);
      results.push(response.data);
    } catch (e) {
      console.log(`❌ Failed to sync ${tc.TC_ID}:`, e.response?.status, e.response?.data || e.message);
    }
  }

  console.log("=== Sync complete ===");
  console.log("Synced items:", results);
}

run();
