import axios from 'axios';
import { getQMetrySettings } from './settingsService';

const getProxyUrl = () => window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' 
  ? 'http://127.0.0.1:3001' 
  : window.location.origin;

/**
 * Transforms test cases into QMetry-compatible payload format
 * Format:
 * {
 *   "name": "<Test Case Name>",
 *   "description": "<Optional>",
 *   "testSteps": [
 *     {
 *       "description": "<Step>",
 *       "expectedResult": "<Expected>"
 *     }
 *   ],
 *   "issueLinks": ["<JIRA-KEY>"]
 * }
 */
export const transformToQMetryPayload = (testCase, jiraKey) => {
  // Attempt to parse Gherkin/Steps into lines, or just use the whole text
  const stepsText = testCase.Gherkin || testCase['Step Summary'] || testCase['Test Steps'] || testCase['Steps'] || testCase.Scenario || '';
  const lines = stepsText.split('\n').filter(l => l.trim().length > 0);
  
  const expectedResult = testCase.Expected_Result || testCase['Expected Result'] || '';
  
  const steps = lines.map((line, index) => ({
    stepDetails: line.trim(),
    description: line.trim(),
    testData: '',
    expectedResult: expectedResult,
    id: index + 1
  }));

  const nameVal = testCase.Scenario_Name || testCase['Summary'] || testCase['Test Case Name'] || testCase.name || testCase.TC_ID || testCase['Work Key'] || 'Generated Test Case';

  // Ensure at least one step if none could be parsed
  if (steps.length === 0) {
    steps.push({
      stepDetails: nameVal,
      description: nameVal,
      testData: '',
      expectedResult: expectedResult,
      id: 1
    });
  }

  return {
    summary: nameVal,
    name: nameVal,
    description: testCase.Description || `Generated by TestPilot AI.\nType: ${testCase.Type || testCase['TestCase Type'] || 'Unknown'}`,
    testSteps: steps.map(s => ({ description: s.description, expectedResult: s.expectedResult })),
    steps: steps,
    issueLinks: jiraKey ? [jiraKey] : []
  };
};

export const testQMetryConnection = async (settings) => {
  const PROXY_URL = getProxyUrl();
  try {
    const response = await axios.post(`${PROXY_URL}/api/qmetry/test`, settings);
    return response.data;
  } catch (error) {
    const backendError = error.response?.data?.error || error.message;
    throw new Error(backendError);
  }
};

export const syncTestCasesToQMetry = async (testCases, jiraKey, activeProject) => {
  const PROXY_URL = getProxyUrl();
  
  let settings = null;
  if (activeProject && activeProject.qmetryEnabled && activeProject.qmetryBaseUrl && activeProject.qmetryApiToken) {
    settings = {
      qmetryBaseUrl: activeProject.qmetryBaseUrl,
      apiToken: activeProject.qmetryApiToken,
      projectId: activeProject.qmetryProjectId
    };
  } else {
    settings = getQMetrySettings();
  }
  
  if (!settings || !settings.qmetryBaseUrl || !settings.apiToken) {
    throw new Error("QMetry settings are incomplete. Please configure them in Project settings or global Settings.");
  }

  const results = [];
  
  for (const tc of testCases) {
    if (tc.qmetryId) {
      results.push({
        tcId: tc.TC_ID,
        name: tc.Scenario_Name || tc.Summary || tc.name || tc.TC_ID || 'Already Synced Case',
        status: 'Success',
        qmetryId: tc.qmetryId,
        message: 'Already synced'
      });
      continue;
    }

    const payload = transformToQMetryPayload(tc, jiraKey);
    try {
      const response = await axios.post(`${PROXY_URL}/api/qmetry/sync`, {
        settings,
        payload,
        jiraKey
      });
      results.push({
        tcId: tc.TC_ID,
        name: payload.name,
        status: 'Success',
        qmetryId: response.data?.id || response.data?.key,
        message: 'Successfully synced'
      });
    } catch (error) {
      results.push({
        tcId: tc.TC_ID,
        name: payload.name,
        status: 'Failed',
        qmetryId: null,
        message: error.response?.data?.error || error.message
      });
    }
  }
  
  return results;
};
