import { useState } from 'react'

const Login = ({ onLogin }) => {
  const [formData, setFormData] = useState({
    baseUrl: '',
    email: '',
    token: '',
    storyId: '',
    geminiKey: ''
  })

  const handleSubmit = (e) => {
    e.preventDefault()
    if (formData.baseUrl && formData.email && formData.token && formData.storyId) {
      onLogin(formData)
    }
  }

  return (
    <div className="glass-card animate-fade-in" style={{ maxWidth: '500px', margin: '10vh auto' }}>
      <h1 className="title-gradient" style={{ textAlign: 'center', marginBottom: '2rem' }}>Jira Connector</h1>
      <p style={{ textAlign: 'center', color: '#94a3b8', marginBottom: '2rem' }}>
        Connect to your Jira Cloud to fetch User Stories
      </p>
      
      <form onSubmit={handleSubmit}>
        <label>Jira URL</label>
        <input 
          type="url" 
          placeholder="https://your-domain.atlassian.net" 
          value={formData.baseUrl}
          onChange={(e) => setFormData({...formData, baseUrl: e.target.value})}
          required
        />

        <label>Email Address</label>
        <input 
          type="email" 
          placeholder="email@example.com" 
          value={formData.email}
          onChange={(e) => setFormData({...formData, email: e.target.value})}
          required
        />

        <label>API Token</label>
        <input 
          type="password" 
          placeholder="Jira API Token" 
          value={formData.token}
          onChange={(e) => setFormData({...formData, token: e.target.value})}
          required
        />

        <label>Story ID / Key</label>
        <input 
          type="text" 
          placeholder="KAN-123" 
          value={formData.storyId}
          onChange={(e) => setFormData({...formData, storyId: e.target.value})}
          required
        />

        <div style={{ background: 'rgba(99, 102, 241, 0.1)', padding: '1rem', borderRadius: '12px', border: '1px solid rgba(99, 102, 241, 0.3)', marginBottom: '1.5rem' }}>
          <label style={{ color: '#818cf8', display: 'flex', justifyContent: 'space-between' }}>
            Gemini AI Key (Optional)
            <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer" style={{ fontSize: '0.75rem', color: '#6366f1' }}>Get Free Key →</a>
          </label>
          <input 
            type="password" 
            placeholder="AI Studio API Key" 
            value={formData.geminiKey}
            onChange={(e) => setFormData({...formData, geminiKey: e.target.value})}
            style={{ margin: '0.5rem 0 0', border: 'none', background: 'rgba(0,0,0,0.2)' }}
          />
          <p style={{ margin: '0.5rem 0 0', fontSize: '0.7rem', color: '#64748b' }}>If provided, your test cases and scripts will be generated by Google Gemini 1.5 Pro!</p>
        </div>

        <button type="submit">Fetch & Connect</button>
      </form>
    </div>
  )
}

export default Login
