import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Activity, Play, Zap, Database, Download, CheckCircle, BarChart3 } from 'lucide-react'

const PerformanceTestingPage = ({ story, credentials }) => {
  const [threads, setThreads] = useState(10)
  const [rampUp, setRampUp] = useState(5)
  const [loops, setLoops] = useState(1)
  const [jmxConfig, setJmxConfig] = useState('')
  const [isSimulating, setIsSimulating] = useState(false)
  const [metrics, setMetrics] = useState(null)
  
  // Update JMX whenever thread parameters change
  useEffect(() => {
    const cached = localStorage.getItem(`testpilot_performance_${story?.id}`)
    if (cached && threads === 10 && rampUp === 5) {
      setJmxConfig(cached)
    } else {
      const generatedJMX = `<?xml version="1.2" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.4.1">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Load Verification Suite - ${story?.key || 'KAN'}" enabled="true">
      <stringProp name="TestPlan.comments">Generated by PerformanceAgent</stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Concurrent User Thread" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">${loops}</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">${threads}</stringProp>
        <stringProp name="ThreadGroup.ramp_time">${rampUp}</stringProp>
      </ThreadGroup>
    </hashTree>
  </hashTree>
</jmeterTestPlan>`
      setJmxConfig(generatedJMX)
    }
  }, [story, threads, rampUp, loops])

  const runSimulation = async () => {
    setIsSimulating(true)
    setMetrics(null)
    await new Promise(r => setTimeout(r, 2200)) // Gorgeous visual transition time

    const simulatedMetrics = {
      avgLatency: 245,
      maxLatency: 840,
      minLatency: 45,
      throughput: `${Math.round(threads * 1.5 * loops)} req/sec`,
      errorRate: '0.00%',
      threadPoints: [
        { load: 1, latency: 50 },
        { load: Math.round(threads * 0.25), latency: 120 },
        { load: Math.round(threads * 0.5), latency: 195 },
        { load: Math.round(threads * 0.75), latency: 260 },
        { load: threads, latency: 450 }
      ]
    }

    setMetrics(simulatedMetrics)
    setIsSimulating(false)
  }

  const handleDownload = () => {
    const blob = new Blob([jmxConfig], { type: 'application/xml' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `jmeter_plan_${story?.key || 'KAN'}.jmx`
    link.click()
  }

  const glassStyle = {
    background: 'rgba(30, 41, 59, 0.45)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: '16px',
    padding: '1.5rem'
  }

  return (
    <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
          <div style={{ background: 'linear-gradient(135deg, #84cc16, #22c55e)', padding: '0.7rem', borderRadius: '14px' }}>
            <Activity size={24} color="white" />
          </div>
          <div>
            <h1 className="title-gradient" style={{ margin: 0, fontSize: '1.8rem', background: 'linear-gradient(to right, #a3e635, #22c55e)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
              Load Performance Testing
            </h1>
            <p style={{ color: '#94a3b8', margin: '0.2rem 0 0', fontSize: '0.88rem' }}>
              Formulate JMeter XML thread plans, configure concurrency parameters, and analyze simulated load response metrics.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button 
            onClick={handleDownload}
            style={{
              background: 'rgba(255,255,255,0.05)',
              border: '1px solid rgba(255,255,255,0.1)',
              color: '#cbd5e1',
              padding: '0.55rem 1.1rem',
              borderRadius: '9px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.4rem',
              fontSize: '0.82rem'
            }}
          >
            <Download size={14} /> Download JMeter Config
          </button>
          
          <button 
            onClick={runSimulation}
            disabled={isSimulating}
            style={{
              background: 'linear-gradient(135deg, #84cc16, #22c55e)',
              color: 'white',
              border: 'none',
              padding: '0.55rem 1.25rem',
              borderRadius: '9px',
              fontWeight: 600,
              cursor: isSimulating ? 'not-allowed' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.4rem',
              fontSize: '0.82rem',
              boxShadow: '0 4px 15px rgba(132, 204, 22, 0.3)'
            }}
          >
            {isSimulating ? <Activity className="spin-icon" size={14} /> : <Play size={14} />}
            {isSimulating ? 'Running Simulation...' : 'Trigger JMeter Load Test'}
          </button>
        </div>
      </div>

      {/* Main split */}
      <div style={{ display: 'grid', gridTemplateColumns: '380px 1fr', gap: '1.5rem' }}>
        
        {/* Load Config Panel */}
        <div style={{ ...glassStyle, display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          <h3 style={{ margin: 0, color: '#f8fafc', fontSize: '1rem', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '0.75rem' }}>Thread Load Settings</h3>
          
          <div>
            <label style={{ display: 'block', fontSize: '0.82rem', color: '#94a3b8', marginBottom: '0.4rem', fontWeight: 600 }}>Number of Threads (Users)</label>
            <input 
              type="number" 
              value={threads}
              onChange={(e) => setThreads(parseInt(e.target.value) || 10)}
              style={{ background: 'rgba(0,0,0,0.2)' }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.82rem', color: '#94a3b8', marginBottom: '0.4rem', fontWeight: 600 }}>Ramp-Up Period (Seconds)</label>
            <input 
              type="number" 
              value={rampUp}
              onChange={(e) => setRampUp(parseInt(e.target.value) || 5)}
              style={{ background: 'rgba(0,0,0,0.2)' }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.82rem', color: '#94a3b8', marginBottom: '0.4rem', fontWeight: 600 }}>Loop Count</label>
            <input 
              type="number" 
              value={loops}
              onChange={(e) => setLoops(parseInt(e.target.value) || 1)}
              style={{ background: 'rgba(0,0,0,0.2)' }}
            />
          </div>
        </div>

        {/* Configurations and Graphs */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          
          {isSimulating ? (
            <div style={{ ...glassStyle, padding: '4rem', textAlign: 'center', color: '#94a3b8' }}>
              <Activity className="spin-icon" size={48} style={{ color: '#84cc16', marginBottom: '1.5rem', opacity: 0.8 }} />
              <h3>Simulating High Concurrency Client Threads</h3>
              <p style={{ fontSize: '0.85rem', marginTop: '0.5rem', maxWidth: '400px', margin: '0.5rem auto 0' }}>
                PerformanceAgent is generating XML plans, configuring sockets, and simulating load latency logs...
              </p>
            </div>
          ) : metrics ? (
            
            // ── GLORIOUS PERFORMANCE METRICS & CHARTS ──
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem' }}>
                <MetricBadge title="Avg Latency" value={`${metrics.avgLatency}ms`} color="#84cc16" />
                <MetricBadge title="Max Latency" value={`${metrics.maxLatency}ms`} color="#ef4444" />
                <MetricBadge title="Throughput" value={metrics.throughput} color="#3b82f6" />
                <MetricBadge title="Error Rate" value={metrics.errorRate} color="#10b981" />
              </div>

              {/* Graphic Chart curve */}
              <div style={{ ...glassStyle, padding: '1.25rem 1.5rem' }}>
                <h4 style={{ margin: '0 0 1rem', fontSize: '0.85rem', color: '#a3e635', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                  <BarChart3 size={15} /> Latency Response Curve (Concurrency vs Latency)
                </h4>
                
                {/* SVG Curve chart */}
                <div style={{ height: '180px', width: '100%', position: 'relative', background: 'rgba(0,0,0,0.2)', borderRadius: '12px', padding: '1rem', border: '1px solid rgba(255,255,255,0.03)' }}>
                  <svg width="100%" height="100%" viewBox="0 0 500 120" preserveAspectRatio="none">
                    {/* Grids */}
                    <line x1="0" y1="20" x2="500" y2="20" stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                    <line x1="0" y1="60" x2="500" y2="60" stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                    <line x1="0" y1="100" x2="500" y2="100" stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                    
                    {/* Latency line path */}
                    <path 
                      d={`M 0 100 Q 125 90, 250 70 T 500 20`}
                      fill="none" 
                      stroke="#84cc16" 
                      strokeWidth="3"
                    />
                    
                    {/* Data nodes */}
                    <circle cx="0" cy="100" r="4" fill="#a3e635" />
                    <circle cx="125" cy="91" r="4" fill="#a3e635" />
                    <circle cx="250" cy="70" r="4" fill="#a3e635" />
                    <circle cx="375" cy="48" r="4" fill="#a3e635" />
                    <circle cx="500" cy="20" r="4" fill="#ef4444" />
                  </svg>
                  
                  {/* Legends */}
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.68rem', color: '#475569', marginTop: '0.5rem' }}>
                    <span>1 User</span>
                    <span>{Math.round(threads * 0.5)} Users</span>
                    <span>{threads} Users (Peak Load)</span>
                  </div>
                </div>
              </div>
            </div>

          ) : (
            
            // Default configuration blueprints
            <div style={{ ...glassStyle, display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              <h3 style={{ margin: 0, fontSize: '0.95rem', color: '#cbd5e1', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                <Database size={15} color="#84cc16" /> JMeter Plan Blueprint (.jmx)
              </h3>
              <textarea
                value={jmxConfig}
                onChange={(e) => setJmxConfig(e.target.value)}
                spellCheck="false"
                style={{
                  width: '100%',
                  height: '350px',
                  background: '#020617',
                  color: '#94a3b8',
                  fontFamily: 'monospace',
                  fontSize: '0.82rem',
                  lineHeight: 1.5,
                  padding: '1rem',
                  borderRadius: '12px',
                  border: '1px solid rgba(255,255,255,0.08)',
                  outline: 'none',
                  resize: 'none'
                }}
              />
            </div>

          )}

        </div>
      </div>

    </motion.div>
  )
}

const MetricBadge = ({ title, value, color }) => (
  <div style={{
    background: 'rgba(30, 41, 59, 0.45)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: '16px',
    padding: '1rem 1.25rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.85rem'
  }}>
    <div style={{ background: `${color}12`, padding: '8px', borderRadius: '10px', color }}><CheckCircle size={18} /></div>
    <div>
      <div style={{ color: '#64748b', fontSize: '0.68rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>{title}</div>
      <div style={{ color: '#f8fafc', fontSize: '1.2rem', fontWeight: 700 }}>{value}</div>
    </div>
  </div>
)

export default PerformanceTestingPage
