import axios from 'axios';

const token = "<YOUR_QMETRY_API_TOKEN>";
const baseUrl = "https://qtmcloud.qmetry.com";
const projectId = 10034;
const jiraKey = "KAN-1"; // Or whatever key was used

async function run() {
  console.log("=== Testing real QMetry sync request to identify exact error ===");
  
  // 1. Resolve folder (search/create)
  let folderId = null;
  try {
    const searchResponse = await axios.get(`${baseUrl}/rest/api/latest/projects/${projectId}/testcase-folders/search`, {
      headers: {
        'apiKey': token,
        'Content-Type': 'application/json'
      },
      params: {
        folderName: jiraKey
      }
    });
    const folders = searchResponse.data || [];
    const existing = folders.find(f => f.name === jiraKey);
    if (existing) {
      folderId = existing.id;
      console.log("Found existing folder ID:", folderId);
    } else {
      const createResponse = await axios.post(`${baseUrl}/rest/api/latest/projects/${projectId}/testcase-folders`, {
        folderName: jiraKey,
        description: `Folder for story ${jiraKey}`,
        parentId: -1
      }, {
        headers: {
          'apiKey': token,
          'Content-Type': 'application/json'
        }
      });
      folderId = createResponse.data.id;
      console.log("Created new folder ID:", folderId);
    }
  } catch (err) {
    console.log("Folder resolution error:", err.response?.status, err.response?.data || err.message);
  }

  // 2. Try to sync a testcase with the exact payload structure
  const payload = {
    summary: "TC_001 - Successful login with valid credentials",
    name: "TC_001 - Successful login with valid credentials",
    description: "Generated by TestPilot AI.\nType: Happy Path",
    testSteps: [
      { description: "Given the user is on the login page", expectedResult: "Login page is displayed" }
    ],
    steps: [
      { stepDetails: "Given the user is on the login page", expectedResult: "Login page is displayed", testData: "", id: 1 }
    ],
    issueLinks: [jiraKey],
    projectId: projectId,
    project: { id: projectId }
  };

  if (folderId) {
    payload.folderId = folderId;
  }

  try {
    const response = await axios.post(`${baseUrl}/rest/api/latest/testcases`, payload, {
      headers: {
        'apiKey': token,
        'Content-Type': 'application/json'
      }
    });
    console.log("TC Sync SUCCESS:", response.status, response.data);
  } catch (err) {
    console.log("TC Sync FAILED:", err.response?.status, err.response?.data || err.message);
  }
}

run();
